import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import sidebar from 'docs/apis/sidebar';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  // 使用autogenerated会把文件名当成目录名
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  openApiSidebar: [
    {
      type: "category",
      label: "API文档",
      link: {
        type: "doc",
        id: "apis/clean-docs",
        // slug: "/apis"
      },
      items: require("./docs/apis/sidebar.ts")
    },
  ],
  // sidebars: [
  //   {
  //     type: "category",
  //     label: "API文档",
  //     link: { 
  //       type: "generated-index",
  //       title: "API文档 标题",
  //       description:
  //         "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
  //       slug: "/en/apis"
  //     },
  //     items: require("./docs/apis/sidebar.ts")
  //   }
  // ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
