import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "category",
      label: "Repositories",
      items: [
        {
          type: "doc",
          id: "apis/update-project",
          label: "更新仓库设置",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "apis/delete-project",
          label: "删除一个仓库",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/get-trees",
          label: "获取仓库目录树",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/search-file-list",
          label: "获取文件列表",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/create-project-file",
          label: "新建文件",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/update-file",
          label: "更新文件",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/delete-file",
          label: "删除文件",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/get-blobs-sha",
          label: "获取文件blob",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-repo-languages",
          label: "获取仓库的语言",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/contributors",
          label: "获取仓库贡献者",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/module-setting",
          label: "设置项目模块",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/code-reviewer-setting",
          label: "修改项目代码审查设置",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/repo-archiving",
          label: "仓库归档",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/repo-transfer",
          label: "转移仓",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/transition-1",
          label: "获取项目的权限模式",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/transition",
          label: "更新仓库的权限模式",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/update-push-config",
          label: "设置项目推送规则",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/get-push-config",
          label: "获取项目推送规则",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/fork-repositories",
          label: "Fork一个仓库",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/get-fork-repositories",
          label: "查看仓库的Forks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/upload-attachment-file-with-base-64",
          label: "上传图片",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/upload-attachment-file",
          label: "上传文件",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/update-repo-settings",
          label: "更新仓库设置",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/get-repo-settings",
          label: "获取仓库设置",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-pull-request-settings",
          label: "获取 Pull Request 设置",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/update-pull-request-settings",
          label: "更新 Pull Request 设置",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/update-member-role",
          label: "更新项目成员角色",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/transfer-repo",
          label: "仓库转移",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/project-customized-role-list",
          label: "获取项目自定义角色",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-download-statistics",
          label: "下载次数统计",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/watch-list",
          label: "列出 watch 了仓库的用户",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/star-list",
          label: "列出 star 了仓库的用户",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-raw-file",
          label: "获取 raw 文件",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Branch",
      items: [
        {
          type: "doc",
          id: "apis/get-branches",
          label: "获取项目所有分支",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/create-branches",
          label: "创建分支",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/get-branch-detail",
          label: "获取单个分支",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/create-protect-branch-setting",
          label: "新建保护分支规则",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/delete-protect-branch-setting",
          label: "删除保护分支规则",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/get-protect-branches",
          label: "获取保护分支规则列表",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/update-protect-branches",
          label: "更新保护分支规则",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Commit",
      items: [
        {
          type: "doc",
          id: "apis/get-commit",
          label: "获取仓库的所有提交",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-commit-detail",
          label: "仓库的某个提交",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/repository-compare",
          label: "Commits 对比",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/create-commit-comment",
          label: "创建commit的评论",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/delete-commit-comment",
          label: "删除commit评论",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/get-commit-comment",
          label: "获取仓库的某条Commit评论",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/update-commit-comment",
          label: "更新Commit评论",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "apis/get-project-commit-comment",
          label: "获取仓库的Commit评论",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/edit-branch",
          label: "获取代码量贡献",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/commit-comment",
          label: "获取单个commit的评论",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Tag",
      items: [
        {
          type: "doc",
          id: "apis/get-project-tags",
          label: "列出项目所有的tags",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/create-project-tag",
          label: "创建一个仓库的Tag",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/project-tag-list",
          label: "列出项目保护 tags",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/delete-protected-tags",
          label: "删除项目保护 tag",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/get-protected-tags-info",
          label: "获取项目保护 tag 详情",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/create-protected-tags",
          label: "创建项目保护 tag",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/update-protected-tags",
          label: "修改项目保护 tag",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Issues",
      items: [
        {
          type: "doc",
          id: "apis/create-issue-1",
          label: "创建 issue",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/update-issue-1",
          label: "更新 issue",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "apis/get-project-issue",
          label: "获取仓库某个 issue",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/list-project-issues",
          label: "获取仓库所有 issue",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/list-issue-comments",
          label: "获取仓库某个Issue所有的评论",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/create-issue-comments",
          label: "创建 issue 评论",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/list-all-issue-comments",
          label: "获取仓库所有issues的评论",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-issue-pull-requests",
          label: "获取 issue 关联的 Pull Requests",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-org-issue-labels",
          label: "获取企业某个Issue所有评论",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/create-project-issue",
          label: "创建 issue 标签",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/delete-project-issue",
          label: "删除issue 标签",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/get-issue-operate-logs",
          label: "获取某个Issue下的操作日志",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/list-group-issues",
          label: "获取某个企业的所有Issues",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/list-user-issues-alise",
          label: "获取当前授权用户的所有Issues",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/update-issue-comment",
          label: "更新Issue某条评论",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "apis/delete-issue-comment",
          label: "删除Issue某条评论",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/get-issue-comment",
          label: "获取仓库Issue某条评论",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/user-org-issues",
          label: "获取当前用户某个组织的Issues",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-enterprise-issue-tag",
          label: "获取企业某个Issue所有标签",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Pull Requests",
      items: [
        {
          type: "doc",
          id: "apis/get-pulls",
          label: "获取Pull Request列表",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/create-pull",
          label: "创建Pull Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/pull-request-merge",
          label: "合并Pull Request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/get-pull-request-merge",
          label: "判断Pull Request是否已经合并",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-pull-request-issues",
          label: "获取pr关联的issue",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/create-pull-request-comments",
          label: "提交pull request 评论",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/get-pull-comments",
          label: "获取某个Pull Request的所有评论",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-pulls-1",
          label: "Pull Request Commit文件列表",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/update-pull-request",
          label: "更新Pull Request信息",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "apis/get-pull-request",
          label: "获取单个Pull Request",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-pull-request-commits",
          label: "获取某Pull Request的所有Commit信息",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/create-pull-request-labels",
          label: "创建 Pull Request 标签",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/get-pull-request-label",
          label: "获取某个 Pull Request 的所有标签",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/update-pr-labels",
          label: "替换 Pull Request 所有标签",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/delete-pull-request-labels",
          label: "删除 Pull Request 标签",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/handler-pull-request-test",
          label: "处理 Pull Request 测试",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/handler-pull-request-review",
          label: "处理 Pull Request 审查",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/get-mr-system-notes",
          label: "获取某个Pull Request的操作日志",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/reset-pull-request-test",
          label: "重置 Pull Request 测试 的状态",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "apis/update-pr-testers",
          label: "指派用户测试 Pull Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/reset-pull-request-review",
          label: "重置 Pull Request 审查 的状态",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "apis/set-pr-assignees",
          label: "指派用户审查 Pull Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/delete-pull-request-assignees",
          label: "取消用户审查 Pull Request",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/get-pull-request-files",
          label: "pr提交的文件变更信息",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-enterprise-pr-2",
          label: "企业 Pull Request 列表",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-pr-comment",
          label: "获取Pull Request某条评论",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/update-pr-comment",
          label: "编辑评论",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "apis/delete-pull-comment",
          label: "删除评论",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/get-enterprise-pr-1",
          label: "组织 Pull Request 列表",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-file-content",
          label: "获取文件内容",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Labels",
      items: [
        {
          type: "doc",
          id: "apis/delete-all-issue-labels",
          label: "删除Issue所有标签",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/update-issue-labels",
          label: "替换Issue所有标签",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/update-project-label",
          label: "更新一个仓库的任务标签",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "apis/get-project-all-labels",
          label: "获取仓库所有任务标签",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/create-project-label",
          label: "创建仓库任务标签",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/delete-project-label",
          label: "删除一个仓库任务标签",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/get-all-labels",
          label: "获取某个企业的所有标签",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/query-group-labels",
          label: "分页查询某个企业的标签",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Milestone",
      items: [
        {
          type: "doc",
          id: "apis/get-project-milestones",
          label: "获取仓库所有里程碑",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/create-project-milestone",
          label: "创建仓库里程碑",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/get-project-milestone",
          label: "获取仓库单个里程碑",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/delete-project-mile-stone",
          label: "删除仓库单个里程碑",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/update-project-milestone",
          label: "更新仓库里程碑",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Webhooks",
      items: [
        {
          type: "doc",
          id: "apis/list-all-web-hooks",
          label: "列出仓库的WebHooks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/create-issue",
          label: "创建一个仓库WebHook",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/get-web-hook",
          label: "获取仓库单个WebHook",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/update-issue",
          label: "更新一个仓库WebHook",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "apis/delete-web-hook",
          label: "删除一个仓库WebHook",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/test-web-hook",
          label: "测试WebHook是否发送成功",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Member",
      items: [
        {
          type: "doc",
          id: "apis/add-member-from-group",
          label: "邀请组织成员",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/put-project-member",
          label: "添加项目成员或更新项目成员权限",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/delete-project-member",
          label: "移除项目成员",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/is-project-member",
          label: "判断用户是否为仓库成员",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-project-members",
          label: "获取仓库的所有成员",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/repo-member-permission",
          label: "查看仓库成员的权限",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Users",
      items: [
        {
          type: "doc",
          id: "apis/get-project",
          label: "获取用户的某个仓库",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/create-user-project",
          label: "创建个人项目仓库",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/user-repos",
          label: "列出授权用户的所有仓库",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/user-info",
          label: "获取一个用户",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/user-emails-1",
          label: "获取授权用户的全部邮箱",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/user-events",
          label: "获取授权用户个人动态",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/query-user-public-repos",
          label: "获取某个用户的公开仓库",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/add-user-keys",
          label: "添加一个公钥",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/user-keys-page",
          label: "列出授权用户的所有公钥",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/delete-user-key-by-id",
          label: "删除一个公钥",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/get-user-key-by-id",
          label: "获取一个公钥",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Organizations",
      items: [
        {
          type: "doc",
          id: "apis/create-org-project",
          label: "创建组织仓库",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/get-group-projects",
          label: "获取组织项目列表",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/remove-member-from-group",
          label: "移除授权用户所管理组织中的成员",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/user-orgs",
          label: "列出用户所属的组织",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/auth-user-orgs",
          label: "列出授权用户所属的组织",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/org-user-info-1",
          label: "获取组织成员详情",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-org",
          label: "获取一个组织信息",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-enterprise-member",
          label: "获取企业的一个成员",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/org-user-info",
          label: "获取授权用户在一个组织的成员资料",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/org-members",
          label: "列出一个组织的所有成员",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/enterprise-members",
          label: "列出企业的所有成员",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/org-followers",
          label: "列出指定组织的所有关注者",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/get-issue-extend-settings",
          label: "获取 issue 扩展配置",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Search",
      items: [
        {
          type: "doc",
          id: "apis/search-users",
          label: "搜索用户",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/search-issues",
          label: "搜索 Issues",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/search-repositories",
          label: "搜索仓库",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Oauth2.0",
      items: [
        {
          type: "doc",
          id: "apis/user-info-1",
          label: "使用访问令牌访问用户信息API",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/auth-api",
          label: "认证接口",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/redirect",
          label: "重定向",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/refresh-access-token",
          label: "刷新access_token",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
